[features]
seeds = false
skip-lint = false
[programs.localnet]
spl_token_staking = "8amutinnwkwN4PuysoSGeRgR9bhhN4waGEx2BSqBDQb4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/taylorjohnson/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -r tests/hooks.ts"
